name: Build and Minify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Minify GStime.js
      run: npm run build

    - name: Commit minified file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Build: Minify GStime.js"
        file_pattern: 'GStime.min.js'
